### ISSUE TITLE
go-wayland-scanner library

### ISSUE THREAD

**Issue by Shinyzenith** [rajveermalviya/go-wayland#2]
Hi! it would be extremely beneficial if go-wayland-scanner could be abstracted into a library instead of a binary. 

This would help downstream repositories easily integrate go-wayland into their build system by calling it in a build step programmatically instead of having to look for a binary. Eg: https://github.com/waycrate/NextWM/blob/master/nextctl-go/Makefile#L13 
This reduces complexity to contribution for downstream projects and increases usability.

**Comment by rajveermalviya** [comment]
Hey!

I don't think exposing it as a library would solve your issue.
Instead of installing the binary and then running it, you can directly run it in single step:

```shell
go run github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner@latest [args]
```

Also I would normally avoid using Makefile for any Go binary projects because of some files being missing from the repository for `go install` & `go run` to find (generated files in your case).
Best way to handle it is include the generated files in the repo, and then regenerate & commit when needed.
You can use [`go:generate`](https://go.dev/blog/generate) for this, you can also check how its used [in go-wayland](https://github.com/rajveermalviya/go-wayland/blob/main/wayland/stable/xdg-shell/doc.go)

**Comment by Shinyzenith** [comment]
> Hey!
> 
> I don't think exposing it as a library would solve your issue. Instead of installing the binary and then running it, you can directly run it in single step:
> 
> ```shell
> go run github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner@latest [args]
> ```

Cool! I had tried this earlier but I noticed the commit fixing this. I'll try it again. Thanks for the help.
